### ISSUE TITLE
Why init not main?

### ISSUE THREAD

**Issue by danilobuerger** [eawsy/aws-lambda-go-net#1]
All the examples start the http server from inside `init()` func instead of the usually used `main()` func. Is there a reason behind this? And if yes, could this be documented?

**Comment by fsenart** [comment]
It's all about the way we can have Golang running on AWS Lambda (https://github.com/eawsy/aws-lambda-go). A shared lib is generated and the main content is not taken into account by the compiler (but this is a necessary artifact required by the compiler as described in the [Go design doc)](https://golang.org/s/execmodes).

**Comment by fsenart** [comment]
I've updated the [wiki](https://github.com/eawsy/aws-lambda-go-net/wiki/Getting%20Started#create-a-hello-world-lambda-web-application) (step 4). Is it enough?

**Comment by danilobuerger** [comment]
For me, yes.
