### ISSUE TITLE
api badge points to confusing place

### ISSUE THREAD

**Issue by tleyden** [eawsy/aws-lambda-go-net#3]
It points to here:

https://godoc.org/github.com/eawsy/aws-lambda-go-net/service/lambda/runtime/net

but might be less confusing to point to here:

https://godoc.org/github.com/eawsy/aws-lambda-go-net

**Comment by tleyden** [comment]
Nevermind, I see the apigatewayproxy api linked off of https://godoc.org/github.com/eawsy/aws-lambda-go-net/service/lambda/runtime/net -- I missed it the first time around.

**Comment by fsenart** [comment]
@tleyden I think we should still change the link so that the two doc links will be more accessible.
