### ISSUE TITLE
http.DetectContentType fails to detect posted JPEG upon lambda

### ISSUE THREAD

**Issue by kaihendry** [eawsy/aws-lambda-go-net#6]
https://s.natalian.org/2017-07-04/handler.go fails to detect a posted image is a JPEG, instead it see it as **application/octet-stream**.

Whilst in local testing, https://s.natalian.org/2017-07-04/main.go, it works fine.

My test script is something like:

```
curl -X POST http://localhost:8000/upload \
        -F "file=@test.jpg" \
        -H "Content-Type: multipart/form-data"
```

Sidenote: Wish I knew why it takes so [long to iterate](https://s.natalian.org/2017-07-04/1499178441_2548x1398.png).

**Comment by fsenart** [comment]
@kaihendry please see https://aws.amazon.com/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/#toc_6. You have to specify the exact content-type of your payload.
