### ISSUE TITLE
redirect not working?

### ISSUE THREAD

**Issue by Zambiorix** [eawsy/aws-lambda-go-net#8]
Hi,

Am I correct that aws-lambda-go-net is not passing on a redirect properly to the client?

I think it gets stuck in this component and doing a redirect locally ...

Cheers
Gerd

**Comment by lion3ls** [comment]
@Zambiorix update your package, everything should work as expected now :wink:

**Comment by Zambiorix** [comment]
:-) great, I'll test it immediately!

Another thing, I believe there is a still a bug in the code:

You should always close a response body if a response is present.
Now you have 2 returns leaving the body open (and the socket unavailable for reuse)
1. I am aware that even if you have an err on newClient().Do, there are cases you still get a reponse body.
2. you should immediately close the body after a ioutil.ReadAll(res.Body)

```

res, err := newClient().Do(req)
if err != nil {
	log.Println(err)
	return
}

body, err := ioutil.ReadAll(res.Body)
if err != nil {
	log.Println(err)
	return
}
res.Body.Close()


```

**Comment by Zambiorix** [comment]
It's working :-)

I use redirects to test if cookies are allowed by client, and it now works as expected

Thanks!

**Comment by Zambiorix** [comment]
I would solve the response body closure like this

```

res, err := newClient().Do(req)
if res != nil {
	defer res.Body.Close()
}
if err != nil {
	log.Println(err)
	return
}

body, err := ioutil.ReadAll(res.Body)
if err != nil {
	log.Println(err)
	return
}


```

**Comment by lion3ls** [comment]
@Zambiorix you're right in the fact that the body should be deferred closed before `ReadAll` but for the `Do` function, the general idiom is to defer after checking for errors. See also the commit message. And thank you very much for having reported this problem.

**Comment by Zambiorix** [comment]
great, thanks!
