### ISSUE TITLE
Why listen and serve instead of handling requests in-memory?

### ISSUE THREAD

**Issue by ivy** [eawsy/aws-lambda-go-net#9]
Hi, I may be missing something here so correct me if I'm wrong. What's the reason behind proxying requests and responses over an additional TCP socket when both `apigatewayproxy.Handle` and a developer's `http.Handler` are operating in the *same* process?

Can't we just build an `http.ResponseWriter`, hand it off to a registered `http.Handler` and transform it into an `*apigatewayproxy.Response`? Even better, couldn't `apigatewayproxy.Response` implement `http.ResponseWriter`? There wouldn't be any additional networking, in either case.

Looking forward to your clarification! :smile:

**Comment by fsenart** [comment]
Hi @ivy,

Theoretically, you're absolutely right. But :smile:...
The primary purpose of this project is to allow running **any** existing web application on Lambda behind API Gateway. The main constraint being the fact that all web framework around are built on top of the tcp network listener and the official http package. Also, the only hook we have is this listener. 
The only thing the end user has to do is to configure its framework of interest to use the provided listener and this project will do the necessary underlying stuff to translate requests from API Gateway to Lambda and vice versa.
Hope this explanation is clear enough, please do not hesitate to ask any other detail you may need.
